# Generated by Django 5.2 on 2025-05-15 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapp',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userapp',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
