# Generated by Django 5.2 on 2025-05-15 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='create_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='update_date',
            new_name='updated_at',
        ),
    ]
